### ISSUE TITLE
Discuss ASDF

### ISSUE THREAD

**Issue by nden** [spacetelescope/braindump#1]
Apr 14, 2016

[asdf-standard](http://asdf-standard.readthedocs.org/en/latest/)

[Python implementation](http://pyasdf.readthedocs.org/en/latest/)

`ASDF` versioning is documented here:

https://github.com/spacetelescope/asdf-standard/blob/master/source/versioning.rst

The `#ASDF` line refers to the file format -- how blocks are laid out, how offsets are calculated, etc.  Basically anything a reader would need to know to separate all of the blocks in the file, but not necessarily the meaning of the tags in the `YAML` portion.

The `#ASDF_STANDARD` refers to the `ASDF` standard, including all of the YAML tags and their meanings.  While each YAML tag is individually versioned, the `#ASDF_STANDARD` groups those up into a single version that can be easily checked such that a reader could say "I don't understand this version of the spec, but I'll do my best to load it anyway...".

Also there is some discussion about versioning in this link:

 https://github.com/spacetelescope/asdf-standard/issues/90

**Comment by embray** [comment]
These should be `#ASDF`, etc. not `%ASDF`.  I think originally it was the latter, but we changed it to use `#` since from YAML's perspective that just makes it a comment, and is not invalid YAML.  Just a nitpick, but something to be clear about.

**Comment by nden** [comment]
@embray Yes, you are right. Thanks, I updated the notes above.

**Comment by pllim** [comment]
@perrygreenfield already doing this.
