### ISSUE TITLE
What's new in Python and Numpy

### ISSUE THREAD

**Issue by nden** [spacetelescope/braindump#13]
Now that build 7 is done (is it?) it looks like there's interest in a session (or two) on the above topic.
Is (Thu) Dec 15 a good day for this (please show :+1:  or :-1: )?

Also we need two volunteers to prepare the two topics. Please volunteer here or send me an email.

**Comment by nden** [comment]
We need to postpone this. January may be better.

**Comment by jdavies-st** [comment]
I do like the optimism of Build 7 being done (?) back on Nov 23.  =)

**Comment by pllim** [comment]
Build 7 definitely done now since I can't stop getting email notifications from Howard about Trac tickets.

**Comment by jhunkeler** [comment]
Things to look forward to in the future: https://docs.python.org/3.6/whatsnew/3.6.html

🚀

**Comment by pllim** [comment]
What was new in 2016 is not longer new.
