### ISSUE TITLE
Git: should we rebase or pull/merge?

### ISSUE THREAD

**Issue by eteq** [spacetelescope/braindump#18]
Discussion of when pulling/merging is better/worse than rebasing. @eteq can frame the discussion and his attitude about this.

**Comment by pllim** [comment]
Rebase!!! 😉  (and squash too... why not???)

**Comment by sosey** [comment]
interactive rebase-squash

**Comment by jdavies-st** [comment]
I would be happy to contribute to this discussion in a non-denominational way.

**Comment by eteq** [comment]
Perhaps @drdavella can tell us about ``git rerere`` (the best/worst-named git command... and that's saying something)

**Comment by drdavella** [comment]
I already mentioned it in #23!

**Comment by drdavella** [comment]
If there are multiple contributors to a PR, squashing means credit will not be given to all contributors, right?

**Comment by pllim** [comment]
Yes, GitHub only allows one author the last time I checked (there's "author1 committed with author2" message if you squash but I don't think they both count in the stats?). You don't have to squash all the commits, but some in a reasonable day. For example, "fix typo" or "fix doc" commits can definitely be squashed into an earlier relevant commit. There is no definite rule; it is a judgement call.

**Comment by pllim** [comment]
I think this is just gang war waiting to happen...
