### ISSUE TITLE
Temporal Logic of Actions

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/braindump#20]
Since it came up in the lunch today, here are couple links to the "Temporal Logic of Actions" literature.

- [The long-winded article in Atlantic](https://www.theatlantic.com/technology/archive/2017/09/saving-the-world-from-code/540393/)

- [Thinking for Programmers by Leslie Lamport](https://channel9.msdn.com/Events/Build/2014/3-642)

- [Lamport's TLA website](http://lamport.azurewebsites.net/tla/tla.html)

**Comment by drdavella** [comment]
This sounds very interesting and useful, but I have to say that the title makes it sound more like a new-age self-help philosophy than a rigorous framework for software validation.

**Comment by pllim** [comment]
> it sound more like a new-age self-help philosophy

The lunch item for this session should be 🥑  toasts.
