### ISSUE TITLE
Should we test on Windows platform? How?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/braindump#21]
(I want to see how fast this one is closed as "wont fix".)

**Comment by drdavella** [comment]
Maybe if I can make any progress using free (yes free! as in beer!) Windows VMs for doing local testing, I could have something to contribute here.

**Comment by pllim** [comment]
And then hook Jenkins up to the Windows VM? Is that possible?

**Comment by pllim** [comment]
@sosey asked for a Windows laptop.
