### ISSUE TITLE
Advanced git workflow

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/braindump#23]
I see this topic as distinct from github workflows, although there will probably be some overlap. I think it would be useful to talk about how git can be used locally to aid a development workflow, and some of the more 'advanced' git features that not all users may be aware of, including:
- git gui
- git grep
- git reset
- git rebase
- git reflog
- git rerere

It might also be useful to talk about git integration with shell environments, including plugins that allow for tab completion of git commands and commits.

**Comment by eteq** [comment]
Might be this is the same as #18?  Although maybe these are different topics... (#18 could be more "best practices" and less "learn how to use git")

**Comment by pllim** [comment]
The auto-completion is pretty sweet. I think @jhunkeler hooked me up with it.

https://stackoverflow.com/questions/12399002/how-to-configure-git-bash-command-line-completion

**Comment by drdavella** [comment]
@pllim cool! I'm actually using `zsh` and plugins for `oh-my-zsh` but to each his/her own 😄

**Comment by larrybradley** [comment]
I also use `zsh`.  I tried `oh-my-zsh` a long time ago, but found it to be slow and bloated (I didn't need/want most of it).  I currently use `prezto`.

**Comment by pllim** [comment]
There is in-house training for this. For 2019: https://innerspace.stsci.edu/display/INSTraining/Git+and+Python+Training+Series+2019
