### ISSUE TITLE
Blind leading the blind: Chase the memory leak

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/braindump#28]
Upvote to listen to the mind-numbing story of ~~resolving~~doing an end-around of the `Spec2Pipeline` memory leak. Punchline: the reason is still unknown, but one of the beast's heads have been removed.

**Comment by drdavella** [comment]
Maybe this would be a good opportunity to talk about tools for C instrumentation like `valgrind` and various sanitizers? And maybe `gdb`?

**Comment by jdavies-st** [comment]
I assume this would let me learn more about profilers?  If so, you have my vote.

**Comment by jhunkeler** [comment]
If you demo `gdb` make sure you have https://github.com/gdbinit/Gdbinit installed.
Everyone will "oooo" and "ahhh".

**Comment by pllim** [comment]
@drdavella -- Using `valgrind` with Python does not seem to be straightforward (see https://code.google.com/archive/p/distnumpy/wikis/valgrind.wiki). If you have any tips on this, let us know!

**Comment by drdavella** [comment]
No, I don't have a lot of experience with that, just with pure C code. I wasn't sure whether `Spec2Pipeline` was pure C or Python extension code. I could look into this kind of thing more though.

**Comment by hbushouse** [comment]
Spec2Pipeline is pure python.

**Comment by drdavella** [comment]
Yikes!

**Comment by eteq** [comment]
Some possible tools to throw into the discussion if time allows:

* https://github.com/fabianp/memory_profiler
* https://github.com/joerick/pyinstrument
* https://github.com/rkern/line_profiler

Would love a session on profiling mixed C/python code, though!  I tend to do the simplest thing of building quick-and-dirty Cython wrappers in a notebook and using the ``%%time`` cell magic.  But there must be better tools out there that leverage C profiling tools.  Might be  a separate topic you could add if we don't get to it for this one, @drdavella?

**Comment by pllim** [comment]
Thought we did that.
