### ISSUE TITLE
Hubble machine learning

### ISSUE THREAD

**Issue by pllim** [spacetelescope/braindump#34]
I volunteer @brechmos-stsci to talk about creating HAL... I mean, machine learning using Hubble data.

**Comment by brechmos-stsci** [comment]
I'm sorry, ~Dave~ @pllim . I'm afraid I can't do that.

Ok, yes, I would be interested...

**Comment by perrygreenfield** [comment]
Daisy, Daisy

**Comment by pllim** [comment]
I think this was done a while back.

**Comment by brechmos-stsci** [comment]
It was!  :)
