### ISSUE TITLE
Emacs org mode

### ISSUE THREAD

**Issue by pllim** [spacetelescope/braindump#41]
@stscieisenhamer , please show us the way!

**Comment by sosey** [comment]
vi4eva

**Comment by stscieisenhamer** [comment]
so we're going to play this game eh? open issue and tag someone else to handle it plus flame-war. hmmmm, I like. But much upvote must occur.

**Comment by nden** [comment]
Please add me to the invite.

**Comment by nden** [comment]
If we end up doing a braindump we should mention it on slack python channel. There might be others interested in this in other divisions.
