### ISSUE TITLE
Using custom STScI template locally and on RTD - works!

### ISSUE THREAD

**Issue by sosey** [spacetelescope/braindump#8]
I got the custom template for our docs working locally and on RTD.  Here's an example of what it looks like:

http://wfc3tools.readthedocs.io/

If you want to use it with the repo that you manage, edit your conf.py to include:

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    "collapse_navigation": True
    }
html_logo = '_static/stsci_pri_combo_mark_white.png'
html_static_path = ['_static']
html_context = {
    'css_files': [
        '_static/css/custom.css',
    ],
}

html_last_updated_fmt = '%b %d, %Y'
html_sidebars = {'**': ['globaltoc.html', 'relations.html', 'searchbox.html']}

You can copy the corresponding logo and custom.css files from the wfc3tools package.

**Comment by pllim** [comment]
The template is not maintained anymore, and better ones are out there in the Python world.
