### ISSUE TITLE
JWST Associations

### ISSUE THREAD

**Issue by nden** [spacetelescope/braindump#9]
Jonathan will tell us all about them.

Thu, Aug 11, noon
Cafecon

**Comment by SaraOgaz** [comment]
Will there be webex?

**Comment by nden** [comment]
I'll set up webex if you need it.

**Comment by nden** [comment]
Reminder: Today, at noon, Cafecon - discuss JWST associations.
Send me an email if you need webex info.

**Comment by stscieisenhamer** [comment]
Tutorial up. See PR #10
